### ISSUE TITLE
Add CTA button

### ISSUE THREAD

**Issue by jennjunod** [Teach-Jenn-Tech/website#4]
Add CTA button and social information near about you

![image](https://user-images.githubusercontent.com/77285384/213179451-64052172-d8ea-42f4-88e7-2784005581cf.png)

**Comment by jennjunod** [comment]
Feedback from @hola-soy-milk

**Comment by jennjunod** [comment]
@hola-soy-milk could you take a look at this, please? I got the CTA button added in src/components/intro.astro but I can't figure out how to get the href on line 27 to connect to the footer with all the social links.

**Comment by hola-soy-milk** [comment]
Hey! I saw you closed this. I gave the button a whirl and it looks good!

Do you think it might be even better to have it open your email address for sending?
