### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jennjunod** [Teach-Jenn-Tech/website#8]

**Comment by jennjunod** [comment]
Feedback will be from from @ajcwebdev 🤣

**Comment by hola-soy-milk** [comment]
For what it's worth, this looks solid so far. Instructions on getting the site running locally are solid.

Some suggestions:

- [ ] [Contribution guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)
- [ ] A description of what this repo is (your website, etc)
- [ ] A link to the live vercel/deployed URL

**Comment by jennjunod** [comment]
Updated contribution guidelines to coming soon and the rest were updated
