### ISSUE TITLE
Social Links Formatting 

### ISSUE THREAD

**Issue by jennjunod** [Teach-Jenn-Tech/website#9]
"i found this slight style bug on mobile, I'm guessing you could fix this by removing the height in CSS on that box"

![image](https://user-images.githubusercontent.com/77285384/213187901-2b2276db-3b43-467b-abb5-df9f75b40e7b.png)

From Maple

**Comment by jennjunod** [comment]
Feedback from @itsMapleLeaf

**Comment by hola-soy-milk** [comment]
Interesting! I suspect it comes from the [footer component's tailwind](https://github.com/Teach-Jenn-Tech/website/blob/main/src/components/footer.astro#L54):

`relative grid grid-cols-2 gap-4 sm:grid-cols-4`

Specifically, it says that on small screens, each row of icons should have 2 elements, or columns.

Maybe trying `grid-cols-3` might make a good workaround?
